### ISSUE TITLE
A07 API

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#10]
- Som användare vill jag kunna styra kartans initialt aktiverade funktioner och/eller data genom URL parametrar så att jag kan styra grundläggande delar av kartan utan att behöva skapa en ny karta.
  Http://sbkvmgeoserver.malmo.se/rest/2.0/map-dev/index.html?config=configs/pbatlas.js&id=6609,6508 (…)
- Så att jag kan styra vissa av kartans funktioner utan att behöva programmera eller administrera kartan, samt för att underlätta integrering med andra applikationer (såsom Miljöreda).

**Comment by RayTimlin** [comment]
Detta måste vi utreda vidare. En kollega i GK har tittat på detta (mot MapInfo) men har inte fått den att fungera. En centerpunkt istället för MapExtent vore bra.

T ex - http://webgistest.gkmalmo.local/spatialmap?profile=csm_statistikkarta&mapext=117694.60189506%206162386.2993683%20121056.20189506%206164176.6993683&sessionid={A9B28F21-C574-4DFC-9543-C88A109C9640}

Verktyget "visa koordinat" kan innehåller kod som kan lösa detta.

**Comment by ulfmin** [comment]
Finns i CSM
