### ISSUE TITLE
A08 Visa alla träffade objekt

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#11]
- Som användare vill jag se alla objekt som träffats av ett klick i kartan för att kunna a) exportera till rapportfunktion eller b) kunna välja ett av objekten

**Comment by mozvey** [comment]
Det finns ett verktyg (Download) som man kan välja ett område och välja en list av skikten och exportera dessa valda objekter till olika formater och olika koordinat system. Nu funkar inte detta bra i WebGIS.

**Comment by ulfmin** [comment]
Bra. Men arbeta vidare med Rapport.

**Comment by ulfmin** [comment]
Ingår i blixten
