### ISSUE TITLE
A11 Configfil/databas

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#14]
- Som administratör vill jag att så mycket som möjligt ska kunna konfigureras i configfilen/databasen. Det gäller bl.a. vilka lager och vilka verktyg som ska vara med samt konfigurering av lager och verktyg. Detta för att man bara ska behöva gå in i en fil/databas när man skapar en produkt.
- Ett exempel är hur plan och byggatlasens configfil är uppbyggd. I Kristianstad har man motsvarande fast i databas.

**Comment by RayTimlin** [comment]
För "nybörjare" går SSM GUI bra att kunna enkel att anpassa den XML config som styra olika profiler/karta.

Man kan också välja att jobba direkt med XML filer
