### ISSUE TITLE
A12 OVERLAYMENY

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#16]
- Som användare vill jag kunna välja kartlager att lägga ovanpå bakgrundskartan. I menyn vill jag kunna se metadata om lagret samt lagrets kartsymbol. Man ska kunna se om ett lager är klickbart i menyn.
- Jag vill kunna  filtrera lager i lagerlistan med fritextsökning. Jag vill även kunna lägga till och ta bort lager från en bruttolista.
- Som administratör vill jag kunna lägga in lager i overlaymenyn med metadata och kartsymbol.
- Det ska vara enkelt att lägga till lager efter kartans initiering via modulens API (förberedande för att kunna lägga till lager från bruttolista i senare versioner)
- Ett exempel är när jag som användare vil välja att se ett eller flera lager ovanpå vald bakgrundskarta.

**Comment by RayTimlin** [comment]
Finns olika sätt att filtrera och tar framme lager t ex i supersök.

Metadata lösningen är inte jätte bra och är baserats på att komma till en annan webbsida istället för en pop-up sida som SMAP

**Comment by ulfmin** [comment]
Cartesia gör lagermeny i minst 3 steg och Z-index
