### ISSUE TITLE
A13 Startruta

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#17]
- Som kartadmin vill jag kunna konfigurera en startruta som visas i initialt i kartan samt kan togglas med en knapp (valfritt) samt med valfri text/html och andra inställningar såsom bredd och komihåg mitt val (t ex visa ej nästa gång).
- För att informera användaren om något när kartan initierats.

![image](https://cloud.githubusercontent.com/assets/5473068/17849270/4e69f964-6858-11e6-913d-7524a11ad334.png)

Samma funktioner som pb-atlas.

Text läggs i profile.xml

Visa inte igen sparas i en cookie. Om man ger cookie nytt namn ska startrutan visas för alla.

Se till så att storlek på startruta anpassas efter antal tecken. Automatiskt eller manuellt. 

Beskrivning av konfiguration i slutet av issuen.

**Comment by RayTimlin** [comment]
Går bra med att konfiguera en startruta i XML (och SSM tror jag) som admin.

Man kan spara position och lager med hjälp av favoriter verktyg.  Finns också ett verktyg som kan ta dra ut URL som man kan använda senare

**Comment by ulfmin** [comment]
Bra men anpassa.

**Comment by RayTimlin** [comment]
"För att informera användaren om något när kartan initierats." -> Eftersom detta gäller jquery och kopplingen till XML teknik som GK har redan jobbat med, kan detta vara intressant att utreda även innan utbildningen.

**Comment by MozafarVeysipanah** [comment]
Lägg till visa endast den här gången.

**Comment by RayTimlin** [comment]
För att informera användaren om något när kartan initierats:

Är klar med ett först utkast - kan demonstrera detta i ett möte. Det går att koppla att skriva in text i en profil.xml till en lapp/startruta som kommer upp
Nästa steg, tror jag är att gå igenom den har med @johanlahti  och @MozafarVeysipanah efter semestrar och i utbildningen. T ex jag fick jobba med standard kod istället för att skapa custom.

**Comment by RayTimlin** [comment]
1. Bättre placeringen
2. Draggable
3. Mindre text
4. Expandera
5. Dokumentation - deploy.xml. Readme.md Hur se din ut i administrationsverktyget.
6. Testa på IE11, Edge, Chrome

**Comment by RayTimlin** [comment]
Cannot get expandable to work, Edge doesnt work with windows 7 (but have tested on IE). Will be getting window 10 within a month so can test. Also not sure of best way with text files.

**Comment by RayTimlin** [comment]
1. Fixa så man kan tvinga fram ny startruta.
2. Expandable?
3. Bättre dokumentation och sätt in olika profiler på Mmapdev
4. Readme.txt hänvisar till html.
5. Text ska lite större (inte samma som global).

Modul ska vara klar 27 april

**Comment by RayTimlin** [comment]
1. Lägg till timme till datum för att tvinga fram startruta
2. Text följer inte med när expanderar ruta nedåt
3. Ulf testar
4. Ulf testar
5. Ulf testar
6. Lägg in global startruta i configfil, ska visas för hela siten. Avsedd för varningstext
7. Ta bort nummer på _nyheter i configfil. Så man enkelt kan skriva in text så att senaste nyheten visas överst

Klart 8 maj

**Comment by ulfmin** [comment]
Lägg modul på
G:\Projekt\mMap-Forvaltning (annmun2)\Kartverktyg\moduler\egenutvecklade\för_testning\startruta
så Ulf kan testinstallera

**Comment by ulfmin** [comment]
Möte Ulf o Ray 8 maj 2017
1. Ändra till Version1, Version2 Version3 etc. För att tvinga fram startruta (använd inte datum)
6. Warningsruta (profil och global) Placera i mitten av karta och gör rutan större

**Comment by ulfmin** [comment]
Klar för testning 7 juni. Readme-fil ska också vara klar

**Comment by RayTimlin** [comment]
Updated so is more responsive to when the screen size is adjusted. Also checked against 3.12 in different browsers.

**Comment by ulfmin** [comment]
Ej krav på att den ska vara med i grundplatta. Det är ett önskemål

**Comment by ulfmin** [comment]
Flyttad till Teams
