### ISSUE TITLE
A14 KOPPLING TILL VALFRITT API (APPLIKATION), REGISTRERING AV NY POST.

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#18]
- A. Som användare vill jag kunna klicka i kartan och öppna en annan webbsida där jag skickar applikationens adress samt koordinaterna eller annat id som parametrar.
- B. Som användare vill jag lägga till en ny post i en relationsdatabas genom att klicka i kartan. Då ska databasen öppnas (URL) och easting och northing skickas med som parametrar.  Posten som skapas ska innehålla easting och northing.
- Som administratör vill jag kunna ange applikationens adress samt attributnamnet på x och y koordinaten eller id för objektet.
## 
- A. Jag vill kunna öppna tex Snedbilder, Gatuvy mm som öppnas med den punkten jag klickat i (applikationen öppnas då med den punkten centrerad, förutsatt att dess API stödjer ett anrop med x & y koordinat). Denna funktion kommer att kunna användas mot många 3:e-parts applikationer. Denna typ av anrop vill jag även ha i popuprutor och i "visa rapport" för gatuvy: http://sbkvmgeoserver.malmo.se/cyclomedia/index.html?posx=117337.40870311481&posy=6162235.476558599
- B. Ett exempel är verktyget "Registrering NBK" i PBAtlas. Jag klickar där  i kartan där karttan. Sen öppnas nybyggnadskarteregistret. En ny post skapas och easting, northing jäggs in i posten automatiskt.
- URL:en ser ut såhär gör regostrering NBK: http://sbkspace.malmo.se/nbk/nbkinsert.aspx?easting=117369&northing=6165946

**Comment by RayTimlin** [comment]
A. Tror GK har redan gjort med anpassningar av linx verktyg dvs sneddbild finns i GKs WebGIS

B. Detta ska utvecklingsgrupp behöver diskutera

**Comment by ulfmin** [comment]
Bra i CSM

**Comment by ulfmin** [comment]
Mozafar arbetar med denna. Administratör sak kunna lägga till fler knappar med länk i en konfigurationsfil.
Problem med att göra den i Swecos modultänk. Problem med global map-click. M ska prata med Nariman. 
Modul ska vara klar 15 maj.

**Comment by ulfmin** [comment]
Arbetsnamn LINX

**Comment by ulfmin** [comment]
Klar för testning 7 juni. Readme-fil ska också vara klar

**Comment by ulfmin** [comment]
Flyttad till Teams
