### ISSUE TITLE
A15 PLATSRAPPORT (KAKFORM)

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#19]
- Exportera träffade objekt till rapportfunktion som fungerar enligt nedan. Översikten för träffade objekt sköts av "Visa alla träffade objekt" (id=103).
- Som användare vill jag få information (attributdata), ur ALLA kartskikt, när jag klickar på valfritt ställe i kartan. Den XY-koordinat som jag klickar på - ska kontrolleras mot alla kartskikt, som anges i ex en specifik  platsrapport-config-fil, och kartskikten med objekt på denna koordinat presenteras i en lista = Platsrapport. Det är bara kartskikt med ett "träffat objekt" om skall visas i platsrapporten.
  Det skall sedan  vara möjligt att klicka på dessa olika objektsträffar och se dess attributdata i ett "Detaljfönster". 
-  FK har en inställning i configfilen där det objekts kartskikt/kartskiktsgrupp tänds automatiskt.
  Träffarna skall visa objekt från kartskikt UTAN att dessa kartskikt måste vara "iklickade" i legenden.
  Merparten av våra kartskikt ska finnas med i denna config-fil.
-  FK önskar att denna Platsrapport dockas till kartfönstrets ena sida, EJ visas mitt i kartan. Möjligt att det skall finnas en inställning för önskat visningsläge av denna dialogruta.
-  Det skall även vara möjligt att fånga attributdata från rasterlager (ex MF bullervärden). Se punkten KLICKBARA RASTERDATA (MF).
-  Det vore även bra att denna markering i kartan kunde göras a´la Blixten d v s Ange om markeringen skall vara punkt, linje eller polygon samt huruvida den ritade markeringen även skall ha ett "buffertområde". Se punkten SELEKTERING MED RITVERKTYG (GK).
## 
- Detta klickning i en "tom karta" ger mig den snabbaste informationen om vad det finns för objekt på en plats som jag som handläggare/projektledare hanterar för närvarande. Det kan vara avtal, projektområden, fastighetshets- och ägarinformation, detaljplaner, skötsel, besiktning m m.
  Om denna funktion kan "se över" förvaltningsgränserna kan GK, Miljöförvaltning och FK se varandras verksamheters intresse/ärende som sammanfaller på samma plats.

**Comment by mozvey** [comment]
Det finns bara infoklick verktyg i WebGIS idag som är liknade till FK verktyget men med nåt annat form. 
[Infoknapp.pdf](https://github.com/malmomap/mmap-modules/files/230004/Infoknapp.pdf)

**Comment by ulfmin** [comment]
Köp av Konsult

**Comment by ulfmin** [comment]
Ligger på #46
