### ISSUE TITLE
A16 Visa fler kartor

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#20]
- Som användare vill jag kunna klicka på en knapp som endast länkar mig vidare till en samlingssida med Malmös övriga kartor.

**Comment by RayTimlin** [comment]
Finns profil selector som innehåller alla CSM kartor.

Tror att skapa en särskild verktyg som har knapp med länker till andra karta är inte ett stort jobb.
Linx är ett exempel av hur vi kan gör detta
