### ISSUE TITLE
A17 KOPIERA LÄNK

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#21]
- Som användare eller webbadministratör vill jag kunna få upp en länk som återskapar nuvarande karta (så långt som möjligt) WYSIWYG. Även för att bädda in karta som iframe. Logiken för att generera länken förutsätts skötas av API:et.
- För att kunna visualisera specifik information som finns i kartan men annars måste aktiveras manuellt av användaren.

**Comment by mozvey** [comment]
Vi ska visa Direktlänk verktyg och diskutera om det ska uppnå behövet.
