### ISSUE TITLE
A18 MÄT

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#22]
- För samtliga nedan: Enskilda punkter ska kunna flyttas eller raderas under pågående mätningar.
- Mäta punkt: Som användare vill jag kunna klicka i kartan för att få information om klickningens koordinat i koordinatsystemen X
- Mäta linje: Som användare vill jag kunna klicka i kartan två gånger för att få information om längden på sträckan mellan punkterna
  Som användare vill jag kunna klicka i karta flera gånger för att få information om längden på sträckan mellan punkt 1-2, 2-3 osv samt summerad läng av hela sträckan.
- Mäta yta: Som användare vill jag kunna klicka i kartan tre eller flera gången för att få information om area för den yta som avgränsas av klickningarna. Därefter vill jag kunna skapa ytterligare ytor genom tre eller flera klickningar på anndra platser. De olika platsernas ytor ska adderas

**Comment by RayTimlin** [comment]
Punkt - ok
Linje - Summerad plus senaste segment
Yta - Summerad plus senaste segment
