### ISSUE TITLE
A19 RITA

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#23]
- Som användare vill jag kunna rita in en punkt i kartan. Punkten ska visas som symbol och en texte ska kunna skrivas till punkten.
- Jag vill även kunna rita en punkt,  linje eller en yta och skriva in en text. Man måste kunna rita flera objekt.
- Man ska kunna välja färg på objekten. Om det är en punkt ska man även kunna skriva välja en symbol.
- Det jag ritat i kartan ska vara med när jag skickar en länk av aktuell karta
## 
- Ett exempel är när jag ska visa en mötespunkt eller bra löpslinga en lämplig yta för för utelek till en kollega. Jag vill då först rita detta i kartan med text och sedan maila en kartlänk med denna information.
- Det kan även vara när vi ska göra en karta för en konferens. Jag vill då visa i kartan var hotellen ligger, var konferensen är. Var busshållpats ligger.
- Det är bra om man kan ha punktsymboler som passar för detta och även symboler med siffor och bokstäver (detta underlättar koppling med lista som beskriver vad de olika symbolern visar för objekt/funktion)

**Comment by mozvey** [comment]
Liknade verktyg i WebGIS är Workspace men det är begränsad.  Det finns möjlighet att rita objekter (Punkt, linje och polygon, text , ..) och välja färg men man kan inte välja en symbol t ex. Också när man skicka länken till en kollege till exempel kommer inte workspace med utan hen måste öppna workspace manuelt.
