### ISSUE TITLE
A20 SÖKFUNKTION (AUTOCOMPLETE)

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#24]
-   Som användare vill jag ha en enkel Snabbsökfunktion. Det ska vara en dialogruta som ligger uppe i verktygsmenyn där jag kan skriva in ett namn eller värde som jag vill se den geografiska utbredningen på. KLICKBAR SÖKMARKÖR MED KONFIGURERBAR POPUPRUTA
-   Jag ska kunna söka på del av ord, ex "fant" ger även träff på "elefant". Dock skall de ord som ”börjar på” komma överst i listan ( ex elefant) och de som ”innehåller” ska komma sist i listan (ex fant). HA KVAR (EN ALLMÄN) AUTOCOMPLETESÖK
-   VID AUTOCOMPLETE VISAS ÄVEN TYP AV OBJEKT INOM PARENTES (ex byggnad, kvarter, projektnummer, detaljplan)
-   VISA OBJEKTETS UTBREDNING MED HIGHLIGHTNING (streckad linje runt om, ej helfylld färgad polygon).
-   Det skall vara möjligt att, i en configfil, att välja om man vill att attributvärdena till det sökta objektet skall visas i en ”pratbubbla” mitt på kartan eller som en ”dockad” funktion i kartans ena sida (som FKKartans Platsrapport).
-   Exempel på objekttyper: Fastighetsbeteckning, Kvarter, Trakter, Gatuadress med nummer, Plannummer, Byggnader, Delområde, orter i Skåne, vattendrag, platser som torg m m (POI-db måste väl finnas kvar?) 
  Specifikt för FK: objekt- och projektnummer, fastighetsbeteckningar i Skåne, historiska/avregistrerade fastighetsbeteckningar
-   ÄVEN KOPPLING TILL MILJÖREDA ÖNSKVÄRT PÅ T EX EN FASTIGHET

**Comment by RayTimlin** [comment]
"Supersök" funktion verkar uppfyller den flesta här. Vore bra att titta närmare punkt 2 och 5.

**Comment by RayTimlin** [comment]
Har kört en test mot PostGIS och bekräftar att S4/supersök fungera med den och Oracle

**Comment by RayTimlin** [comment]
Detta funktion behöver en ordentligt lathund för att hjälpa andra inom GK och andra förvaltningar kommer igång med den. 
Långsiktigt skulle jag kolla på andra kommuner som har utvecklat detta verktyg på ett intressant sätt t ex Kungsalv

**Comment by ulfmin** [comment]
Septima klarar det som atuto-complete-modulen ställer som krav. Lathund är klar.
