### ISSUE TITLE
A21 HJÄLP

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#25]
- Hjälpfil, även hjälp i varje verktyg. Ska vara lätt att ändra i, ex en pdf som ligger på ett sälle som är lätt att byta ut.
  Ev bör den delas upp i flera hjälpfiler. En för karta, en för funktioner, en för "skapa egen karta" o s v
- (Johan): Som användare vill jag få tips/hjälp i kartan hur jag använder funktionerna så att jag inte blir avskräckt från att använda dem eller måste kämpa i timmar för att förstå hur de ska användas.

**Comment by ulfmin** [comment]
Kan Införandegrupp hjälp till att göra lathundar?
Införandegrupp gör lathundar till användare, pratat med Helena och Christian.

**Comment by RayTimlin** [comment]
GIS i GK har skapat en websida för detta:
https://komin.malmo.se/Forvaltningar/Gatukontoret/Stod--service-pa-gk/WebGIS.html

Men jag blir ju väldigt glad att lämna över detta arbete till införande grupp.
