### ISSUE TITLE
A23 PRODUKTVÄLJARE (Jag vill arbeta med..)

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#27]
- Som användare vill jag snabbt kunna växla mellan olika förbestämda lagersammanställningar. Valet kan göras i en listruta.
- Som administratör vill jag ge namn på "produkten" och välja vilka lager som tillhör produkten. Jag vill kunna skapa flera produkter.
- Exempel: jag vill se en karta med miljörelaterade skikt och sen växla till en karta med fastighetsanknutet innehåll.

**Comment by mozvey** [comment]
Tror favoriter fixar detta

**Comment by ulfmin** [comment]
Profil i CSM.
