### ISSUE TITLE
A 24 UTÖKAD SÖKNING (AVANCERAD)

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#28]
- Som användare vill jag kunna utföra en sökning efter attributdata i valfri kolumn i ETT definierat lager för att erhålla en träfflista innehållandes samtliga poster från den efterfrågade sökningen. 
- Sökningen ska kunna innehålla databasfrågor så som:  Innehåller, är skilt från, börjar med, mindre än , större än…
- Det ska vara möjligt att välja i vilken kolumn av attributdata som sökningen ska genomföras
- Som användare vill jag kunna erhålla ett mer avgränsat resultat än supersöken när jag vet i vilket lager och attributdata som efterfrågan information finns

**Comment by RayTimlin** [comment]
[A 24 UTÖKAD SÖKNING.docx](https://github.com/malmomap/mmap-modules/files/203917/A.24.UTOKAD.SOKNING.docx)

Vet inte om detta metod fungera med WMS eller WFS

**Comment by ulfmin** [comment]
Ad-Hoc löser detta
