### ISSUE TITLE
A25 KLICKBAR RASTERDATA

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#29]
- Nivå 1: Som datoranvändare vill jag kunna klicka i kartan för att erhålla information om en enskild rasterpunkts attributdata (oftast gradientvärde)
- Nivå 2: Som datoranvändare vill jag kunna göra en polygonmarkering för erhålla information om det markerade områdets minivärde, maxvärde, median samt medelvärde för rasterpunkternas attributdata (oftast gradientvärde)
- Det är svårt som användare att tolka färgkoder i en legend.

**Comment by mozvey** [comment]
Vi har inte testat.

**Comment by ulfmin** [comment]
Flyttad till Teams
