### ISSUE TITLE
A26 TRANSPARENS

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#30]
- Som användare behöver jag ibland göra exempelvis ett avtalslager lite transparent för att se ägarkartskiktet eller ett ortofoto "genom" avtalets utbredning. Ex för att se hus, gator, parkeringsområden eller dylikt. Det vore bra om alla lager gick att göra transparent.

**Comment by RayTimlin** [comment]
Finns en transparens verktyg kopplade till alla verktyg.

**Comment by ulfmin** [comment]
Finns i CSM
