### ISSUE TITLE
A27 Grafiskt gränssnitt för att konfigurera konfigfil.

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#31]
- Som administratör vill jag kunna ändra i konfigfil med ett grafiskt gränssnitt.
- Exempel. Som administratör vill jag bygga upp och ajourhålla konfigfilen för min förvaltning.

**Comment by mozvey** [comment]
Vi tror att SSM låtar bra för sådana grejer.

**Comment by ulfmin** [comment]
SSM
