### ISSUE TITLE
A28 Inställningar

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#32]
- Som användare vill jag lätt kunna anpassa den information som visas under tiden jag är inne i kartan för att vara flexibel i min visuella informationssökning.
- [INSTÄLLNINGAR: VISA ÖVERSIKTSKARTA, VISA TECKENFÖRKLARING, VISA SKALSTOCK MM]
- I vissa lägen behöver jag mycket information om kartan och de bakomliggande attributen. Vid andra tillfällen behöver jag  en så ren och överskådlig  kartbild som möjligt.

**Comment by mozvey** [comment]
Vi ska visa er inställningar verktyg i CSM.

**Comment by ulfmin** [comment]
Finns: Inställningar i CSM.
