### ISSUE TITLE
A29 Bruttolista med valbara lager

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#33]
- Nivå 1: Som kartadministratör vill jag kunna skapa och anpassa kartor för olika förvaltningar och användning. Detta underlättar användningen av kartverktyget på användarnivå.
  Som användare vill jag kunna lägga till lager från bruttolistan i lagermenyn. Exempel: Lägga till och ta bort skikt och teman från befintlig karta enligt bifogad bild.
- Nivå 2: Som användare vill jag kunna spara det jag lagt till så att det bevaras till nästa gång jag besöker kartan.
- [Utformning av karta utifrån förvaltning/användning]
## 
- Jag som användare vet bäst hur jag brukar arbeta och vilken kartinformation jag har störst nyttav. Kan jag själv ställa in detta är jag mindre beroende av kartadministratörer och arbetar förmodligen effektivare.

**Comment by mozvey** [comment]
Favoriter och temaväljaren nog uppfylla detta

**Comment by ulfmin** [comment]
Finns i CSM
