### ISSUE TITLE
A30 SELEKTERING MED RITVERKTYG (Geometrisökning)

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#34]
- Vill kunna selektera ytor, linjer och punkter i kartan med hjälp av en egendefinierad yta eller linje. En urvalsyta kan täcka (fånga in) alla typer av objekt, En linje ska kunna fungera vid utval av ytor som linjen korsar,. Kan användas vid utrval av fastigheter vid grävning eller gränsdragning.
- Nivå 1: Som användare vill jag rita en punkt, linje eller yta som selekterar allt som intersekteras i underliggande lager. Lager som ska selekteras är tända lager eller lager som administratör anger.
- Nivå 2: Som användare vill jag kunna ange en buffert runt mitt ritade objekt (ej att förväxlas med det andra buffertverktyget som gäller för existerade objekt).
- Som administratör vill jag kunna ange vilka lager som är selekterbara.
## 
- Som användare  vill jag tex kunna se vilka fastigheter som berörs i ett gatuprojekt.

**Comment by mozvey** [comment]
Ad-hoc analys

**Comment by ulfmin** [comment]
Finns i CSM
