### ISSUE TITLE
A32 HISTORISKA FASTIGHETER

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#36]
- Som användare på fastighetskontoret är det viktigt at kunna se historiken och förändringarna i en fastighets utbredning - fastighetsregleringarna.
- DATABASEN: I FKKartan finns en komplicerad funktion, skapad av Sweco, som varje natt läser in 
- Fastigheter_p.shp från GDL i en egen tabell (FASTIGHETER_P_H) via ett skript som jämför förändringar. Endast förändringarna sparas i tabellen. Ex på fält: Typ, fastighet, omrnr, fnr, cfdnr, trakt, fbetnr, fromdate, todate,area. Skriptet går varje vardagsnatt.
- FUNKTION I KARTAN: Lagrets tänds som vanliga lager, då visas dagens aktuella fastighetsgränslinjer. I legenden finns sedan två verktyg för att kunna söka efter förändringar på ett specifikt datum bakåt i tiden (till år 2000), dels ett ”slideverktyg” och ett vanligt kalendarium.
- Problematik att lösa: Bättre attributdata skulle behövas. Svårt att symbolisera historiska och aktuella fastighetsgränslinjer samtidigt tillika med bägges fastighetsbeteckning som label.
  ( ska även gå att gör med andra lager, tex Detaljplan)
## 
- Det finns många handläggare på fastighetskontoret som i sitt jobb behöver veta den historiska utbredningen på en fastighet. Fastighetsskatt, fastighetsjurister, arkivpersonal,förvaltare.

**Comment by RayTimlin** [comment]
Oklart idag hur vi löser detta i CSM.
Det finns något som heter "History Table" inom SSM verktyget oklart om detta lösa.

Undrar om det finns möjlighet med en FME lösning och interna utveckling? Annars kan det vara bra att ta kontakt med leverantör

Sweco Denmark berättade om ett "slideverktyg" ska utvecklas i en framtid version av CSM

**Comment by ulfmin** [comment]
FK har denna.Utveckling av Konsult?

**Comment by ulfmin** [comment]
Sweco har levereat denna men fungerar ej i IE.

**Comment by RayTimlin** [comment]
Hur har Sweco byggd modul (var finns kod förresten). Är det typ 1 eller typ NPM?

**Comment by msfk-annmal** [comment]
Ann-Charlotte testat "datumreglaget" på Chrome, IE11, Edge och Firefox.

Funktionen att dra reglaget bakåt i tiden och att kartskiktet förändrar sig därefter - är OK på alla ovanstående webbläsare.

Kommentar om alla webbläsarna:
1. ÅÄÖ fungerar inte i rubriken på dialogrutan
2. Jag vill ändra default-datum till att vara dagens-1 månad. (INTE dagens-1 år som jag tidigare föreslått)


Dock är själva reglaget (dialogrutan) inte optimalt på IE11:
![skarmklipp1](https://cloud.githubusercontent.com/assets/2434697/21103380/7a6978c8-c082-11e6-906f-ad7df0f32ed9.PNG)

3. Datum och reglage får inte plats i rutan - de radbryts och scrollist skapas i underkanten på dialogrutan.

**Comment by msfk-annmal** [comment]
Testat 2017-01-11 i Chrome, IE och Firefox

1. är nu korrekt (ÅÄÖ)
2. ej åtgärdad (defaultdatum=dagens - 1månad)
3. är rättad MEN!
4. NY fel datumformat på månad (3 tecken!)
![skarmklipp6](https://cloud.githubusercontent.com/assets/2434697/21843167/47f9bcf2-d7ea-11e6-9a88-2d7ebc498a67.PNG)

5. NY De röda fastighetsgränslinjerna kommer inte med vid Utskift

**Comment by ulfmin** [comment]
Hej,
Jag kan inte se något mer än det du skrivit.
Vill du ha med något mer innan jag mailar Sweco.
Borde inte datum vara dagens datum?? Och inte 1 månad tillbaka, lätt att tolka fel o tro att det är dagen datum???

(Jag har ett tillägg, Vill att man i description-tag skriver att det finns readme.html)
Mvh Ulf

Från: Ann-Charlotte Malmros [mailto:notifications@github.com]
Skickat: den 11 januari 2017 10:41
Till: malmomap/mmap-modules
Kopia: Ulf Minör; Author
Ämne: Re: [malmomap/mmap-modules] A32 HISTORISKA FASTIGHETER (#36)


Testat 2017-01-11 i Chrome, IE och Firefox

1.      är nu korrekt (ÅÄÖ)

2.      ej åtgärdad (defaultdatum=dagens - 1månad)

3.      är rättad MEN!

4.      NY fel datumformat på månad (3 tecken!)
[skarmklipp6]<https://cloud.githubusercontent.com/assets/2434697/21843167/47f9bcf2-d7ea-11e6-9a88-2d7ebc498a67.PNG>

5.      NY De röda fastighetsgränslinjerna kommer inte med på Utskrifen

**Comment by ulfmin** [comment]
Bugglista skickad till Sweco 2017-01-16

**Comment by msfk-annmal** [comment]
Punkt 2.  ovan (defaultdatum=dagens datum) är OK

Punkt 5.  ovan Tyvärr, kartskiktet visas varken vid Snabbutskrift eller via verktyget Skriv ut.

**Comment by ulfmin** [comment]
Svar från Nariman

Problemet här är återigen att historiska fastigheter mer fungerar som en fristående modul snarare än ett theme inne i CSM-världen. Detta pga att lagret skulle vara dynamiskt och vi lyckades inte komma på ett sätt att lösa det på inne i spatial server. Nackdelen blir då att vi inte får något gratis när det gäller standardfunktionalitet för themes. Fördelen är att vi kan använda historiska fastigheter på samma sätt som i er tidigare kartlösning. 

- Metadata: Bör vi kunna hantera ganska enkelt. Ca 4h för att få till den funktionen. (inkl installation)
- Transparens: ca 8-16h. 
- Jämförelse: tror tyvärr den tar orimligt mycket tid att försöka knäcka.

**Comment by ulfmin** [comment]
Ska testas i 3.12

**Comment by ulfmin** [comment]
Flyttad till Teams
