### ISSUE TITLE
A33 SKAPA BUFFERT FRÅN OBJEKT

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#37]
- Som användare vill jag kunna selektera ett objekt och baserat på det skapa ett nytt tillfälligt objekt med en angiven buffert så att jag visuellt kan se det tillfälliga objektets utbredning (t ex överlapping med andra geodatalager) eller för att selektera det.
- T ex (använt i ett sammanhang): Tänd delområden i kartan. Jag väljer ett delområde som buffrar selekterat område och använder det buffrade området för selektering av brunnar.
## 
- Så att jag som användare visuellt kan jämföra ett buffrat objekt med andra geodatalager eller för att använda objektet som indata till andra mMap-verktyg.

**Comment by MozafarVeysipanah** [comment]
Ja med Oracle/PostGIS, måste kolla uppe om WFS/WMS.
Ad hoc är verktyget om detta.

**Comment by ulfmin** [comment]
Finns i CSM
