### ISSUE TITLE
A34 UTSKRIFT LÄGESKARTA

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#38]
- Som användare vill jag kunna skriva ut aktuell karta. På utskriften ska även en översiktskarta vara med där man ser aktuellt kartutsnitt.
  Jag vill även kunna lägga till fyra korta texter.
## 
- Ett exemplel är när jag ska skapa kartbilagor till nämndshandlingar. Jag sparar då mycket tid om jag med en musklickning kan få denna utskrift med två kartor och texter. Texterna kan i detta fall vara: Ärende, Ärendenummer, Fastighet, Adress

**Comment by RayTimlin** [comment]
Man kan lägga in egen text i PDF men vi får kolla om det uppnår behov.

Anpassade PDF till vissa användare har vi inte gjort hittills. Kanske detta är något för utvecklingsgrupp

**Comment by ulfmin** [comment]
Se förbättra utskrift (mallar)
