### ISSUE TITLE
A35 REDIGERING

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#39]
- Som användare vill jag kunna lägga till och ändra i punkt, linje, och ytobjekt. Jag vill också kunna ändra i attributen till dessa objekt. Detta för att på ett enkelt och effektivt sätt kunna ajourhålla data. 
- Begränsningar: Då det anses för avancerat att skapa funktioner för att snappa (fästa) objekt mot andra lager (mot samma lager är ok) kan man bara arbeta med fristående objekt, d.v.s. punkter fungerar alltid. Linjer och ytor måste vara enskilda fristående objekt när dessa skapas.
- Ska fungera responsivt (som allt annat).
## 
- Om man kan redigera geografiska objekt genom ett enkelt och avpassat verktyg, kan den anvariga för informationen i de flesta fall själv ha kontroll på sina data.
  Detta skulle innebära att man behöver färre avancerade GIS - verktyg och fler kan dela på ajourhållningen av data.

**Comment by mozvey** [comment]
Vi ska visa Feature Edit, man kan också skapa behörigheter med Permissions Manager

**Comment by ulfmin** [comment]
Finns i CSM
