### ISSUE TITLE
A36 KOPPLING TILL MILJÖREDA:

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#40]
- Som användare vill jag kunna selektera objekt i kartan för att sedan få upp dessa i Miljöredas applikation.  Som användare vill jag också från Miljöreda kunna nå kartan med några förvalda objekt selekterade. http://sbkvmgeoserver.malmo.se/rest/2.0/map/index.html?config=configs/pbatlas.js&id=543,24316    MEN även kunna öppna markerade obkjekt i kartan i MR

**Comment by RayTimlin** [comment]
Kanske går det från Mmap till Miljöreda, det beror på. Vi behöver ett exempel av ett link att titta på

Från Miljöreda till Mmap är inte helt klart men det känns som det borde gå

**Comment by ulfmin** [comment]
j

**Comment by msfk-annmal** [comment]
Se #84
