### ISSUE TITLE
A37 ÅTKOMST AV MMAP I FÄLT

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#41]
- Nivå 1: SOM SMARTPHONE-/TABLETANVÄNDARE VILL JAG KUNNA HÄMTA INFORMATION FRÅN SAMTLIGA LAGER OCH SUPERSÖK I MIN HANDHÅLLNA ENHET NÄR JAG INTE HAR TILLGÅNG TILL EN DATOR
- Nivå 2: SOM SMARTPHONE-/TABLETANVÄNDARE VILL JAG HA ÅKOMST TILL SAMTLIGA MMAP-FUNKTIONER UTAN SÅDANA MED KOPPLINGAR TILL EXTERNA API:ER I MIN HANDHÅLLNA ENHET NÄR JAG INTE HAR TILLGÅNG TILL EN DATOR
- Nivå 3: SOM SMARTPHONE-/TABLETANVÄNDARE VILL JAG HA ÅKOMST TILL SAMTLIGA MMAP-FUNKTIONER I MIN HANDHÅLLNA ENHET NÄR JAG INTE HAR TILLGÅNG TILL EN DATOR
## 
- Många användare har behov av att söka efter lägesbunden data när de jobbar utanför kontoret

**Comment by mozvey** [comment]
Minimap editor plus utvecklingar pågår med att göra CSM mer responsiv

**Comment by ulfmin** [comment]
Minasidor.malmo.se (logga in). Peter Jönsson

**Comment by ulfmin** [comment]
Helena har beställt detta innan sommaren 2016

**Comment by ulfmin** [comment]
Eftersom det är införandegruppens ansvar stängs denna Issue
