### ISSUE TITLE
A38 (dublett redigering (A35))

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#42]
- SOM SMARTPHONE-/TABLETANVÄNDARE VILL JAG KUNNA GÖRA OCH SPARA TEXT-, PUNKT-, LINJE- OCH POLYGONMARKERINGAR I MIN HANDHÅLLNA ENHET FÖR ATT SEDAN HA DESSA TILLGÄNGLIGA I ”MIN KARTA” I DATORN. Lägespunkter bör utgå från den handhållna enhetens positioneringstjänster
- Det är vanligt att användade behöver göra minnesanteckningar kopplade till lägesbunden data i fält.

**Comment by RayTimlin** [comment]
Minimap editor 2 ihop med Feature Edit kommer med CSM 3.11 eller CSM 3.12

Detta är vädligt viktigt att lösa för GK
