### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#47]
asasscv

**Comment by ulfmin** [comment]
ascsa #43

**Comment by johanlahti** [comment]
Hej :e-mail:

**Comment by ulfmin** [comment]
Ramlar detta ner i rätt mapp 
![Image of Yaktocat](https://octodex.github.com/images/yaktocat.png)

**Comment by johanlahti** [comment]
Jajamänsan, det fungerar. Imponerande bild. Kolla din mail också…

Jag testar ändra igen.

**Comment by ulfmin** [comment]
Tack!

Kan du gör ny ändring i issue

Från: Johan Lahti [mailto:notifications@github.com]
Skickat: den 24 mars 2016 13:43
Till: malmomap/mmap-modules
Kopia: Ulf Minör
Ämne: Re: [mmap-modules] Test (#47)

Jajamänsan, det fungerar. Imponerade bild.

**Comment by ulfmin** [comment]
Tack!

Kan du gör ny ändring i issue :)

**Comment by johanlahti** [comment]
Nytt inlägg. :speech_balloon:

**Comment by johanlahti** [comment]
Test igen

**Comment by ulfmin** [comment]
Gött

Från: Johan Lahti [mailto:notifications@github.com]
Skickat: den 24 mars 2016 13:56
Till: malmomap/mmap-modules
Kopia: Ulf Minör
Ämne: Re: [mmap-modules] Test (#47)

Nytt inlägg. [:speech_balloon:]
