### ISSUE TITLE
Metadata (info i popup)

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#48]
Gör metadatapopup som den fungerar i Malmö Stadsatlas.
Ska visa info i iframe. 
Tex http://sbkvmas2.sbkmalmo.local/git/metadata/metadata.aspx?id=sma_forsamling_p

Lägg in kod i basplattform. (mmaptest) när koden är testad och acceptansgodkänd.

Hur är möjligheten att fixa Metadataknappen så metadata visas i popup istället som nu i nytt fönster.

![image](https://cloud.githubusercontent.com/assets/5473068/14107355/f2030ce6-f5b7-11e5-8d63-5e126fd59762.png)

@johanlahti @peterahlstrom

**Comment by RayTimlin** [comment]
Vi i GK har en working solution som fungera kortsiktigt - vi utreder olika lösningar med detta t ex att hämta från txt,html eller anpassa från xlsx filer.

![meta1](https://cloud.githubusercontent.com/assets/13118484/15960299/7f09d180-2eff-11e6-9517-b41b74290230.png)

![meta2](https://cloud.githubusercontent.com/assets/13118484/15960387/d2cc7b6a-2eff-11e6-974a-227ac9b58e98.png)

Långsiktigt behöver ni nog att tänka mer på en lösningen där vi kan hämta detta information från t ex en PostGIS tabell.

**Comment by ulfmin** [comment]
Stina visade nya metadatabasen som Sokigo visat henne och Lotten.
Oklart hur koppling mellan CSM och metadatabasen ser ut. 
Beslut att vi inte går vidare med modulen metadataknapp utan aktivt försöker påverka Sokigo så koppling mellan CSM och metadatabas blir som Malmö önskar.
