### ISSUE TITLE
A02 Visa skala

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#5]
- Som användare vill jag kunna se vilken skala som gäller just nu samt kunna ändra denna genom att klicka på skalan. Det är bra för användare att kunna se en skalststock och aktuell skalnivå i kartfönstret.
  Möjligen skall detta vara valbart per förvaltning via inställningsparametrar (gäller ju för alla moduler). 
  VISA SKALA  (VALBAR)

**Comment by ulfmin** [comment]
Resolutions 0.26458483,0.529168,1.058336 
Visas i:
CSM 1:750, 1:1500, 1:3000
PB-atlas 1:1000, 1:2000, 1:4000

**Comment by mozvey** [comment]
Nuvarande-skala visas i WebGIS som text.Det finns också möjlighet att användare välja sin skal. 
[Uploading skal.docx…]()

**Comment by ulfmin** [comment]
Åtgärd: Utred vilken skala som är rätt. Går det att skapa listruta med cachade skalor? Annars bra.

**Comment by ulfmin** [comment]
Se om det går att göra listruta för att välja cachade skalor

**Comment by ulfmin** [comment]
Har beställt detta av Sokigo. 2016-10-31
De gör geowebbcache-AGS lösning

**Comment by ulfmin** [comment]
Lösning klar. Geowebbcache konfigurerad och klar.
