### ISSUE TITLE
Zoom till ungerfarlig skala verktyg

### ISSUE THREAD

**Issue by RayTimlin** [malmomap/mmap-modules#54]
Vi har fått 2 synpunkter att detta verktyg blir fast ibland (har testat själv och inte haft samma problem).
Undrar om det kan bli en browser  problem?  

Jag undrar om detta är något vi ska ha med i baskarta i alla fäll kolla #5 

![zoom till ungerfarliga skala](https://cloud.githubusercontent.com/assets/13118484/15175004/9d5217d6-1764-11e6-93c6-c6a380136f2d.png)

**Comment by ulfmin** [comment]
Använder befintlig funkion
