### ISSUE TITLE
A43 Användargränssnitt

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#55]
Se över användargränssnitt så det blir enklare och renare.
Ej behöva klicka på (i) för att klicka på objekt i karta. mm mm
Dynamisk teckenförklaring: Lägg till så det går att använda getlegendgraphic.

**Comment by ulfmin** [comment]
##

**Comment by ulfmin** [comment]
Ray undersöker, kan bli så att vi går på 3.12 gränssnitt som är mycket bättre än 3.11

**Comment by RayTimlin** [comment]
Har gått igenom 3.12 gränssnitt ihop med GK kommunikatör.
Slutsats är att 3.12 är mycket bättre och betraktas som good enough utan några små fixar. Jag stannar med skins arbete till 3.12

**Comment by RayTimlin** [comment]
Den jag vill pratat med dig är:

Från Fredrik:

_"VAL AV KARTA. Den första svårigheten som jag tänker på är valet av karta. Om man inte är en rutinerad användare av systemet är det lätt att missa den lilla texten ”ändra karta”. Finns risk att man tror att grundkartan är allt som erbjuds.

Förslag: Kan man få upp ett pop-up fönster när man går in i kartan där du direkt får välja karta innan något öppnas?
Alternativt att du på något sätt måste välja karta innan något öppnas i menyn. Då ser användarna direkt att det finns mer att välja på."

**Comment by ulfmin** [comment]
Vi använder 3.12:s gränssnitt
