### ISSUE TITLE
Förbättra Mätverktyg

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#58]
Ska kunna addera linje och yta (som man gör i FK3).
Tex Yta = 5 + 64 = 69

**Comment by RayTimlin** [comment]
Uppnår den 3.12 versionen denna kravspec?

http://csm.sokigo.se/spatialmap?

![bild](https://user-images.githubusercontent.com/13118484/29173869-e2845b2e-7de4-11e7-9f28-4d74ec20dd69.png)

**Comment by ulfmin** [comment]
Godkänd av Ray, Acm och Ulf. Issuen stängs härmed. 
Önskan att i framtiden alltid visa i m2 oavsett hur stor ytan är men väntar med detta.
