### ISSUE TITLE
Fler val av orto-karta i CSM, typ liknade urval i bef. Plan-bygg-atlas/SBK 

### ISSUE THREAD

**Issue by gerlil10** [malmomap/mmap-modules#59]
På SF utemiljö är det bl.a. en fördel att snabbt kunna konstatera via flygfoto/år när t.ex. en byggnad är uppförd eller riven. Markarea går ifrån eller kommer till, att sköta/drifta. Reglering mot skötsel-entreprenör mm.

**Comment by ulfmin** [comment]
KLAR (fler orton inlagda i grundplatta)
