### ISSUE TITLE
A03 Skalstock

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#6]
- Som användare vill jag kunna få information om aktuell skala samt en skalstock som visar avståndsförhållanden vid aktuell inzoomningsnivå.
- Vid en skärmdump som genererar en bild av kartan med en felaktig upplösning/inzoomning behöver det finnas möjlighet att bedöma avstånd mellan olika punkter mot en skalstock.

**Comment by RayTimlin** [comment]
Behöver nog  mer förklaring om detta

//Ray

[A03 Skalstock.docx](https://github.com/malmomap/mmap-modules/files/223759/A03.Skalstock.docx)
