### ISSUE TITLE
Python PostGIS

### ISSUE THREAD

**Issue by RayTimlin** [malmomap/mmap-modules#63]

**Comment by RayTimlin** [comment]
wAFFLE TEST

**Comment by RayTimlin** [comment]
GK har börjat använda python till aktiviter kopplade till Mmap.
T ex vi använder python för att skapa många XML filer som bygga kartor i Mmap istället för att gör det manuellt. Vi också använda Python för att skapa triggers i databasen som kan styra hur man använda ritningsverktyg t ex man får inte rita cykelställe på icke-kommun mark. Vi har planer för att skapa en "smartare" databas i PostGRES.

Det kan vara intressant att GK dela med sig hur vi använder Python med andra förvaltningar angående bättre data noggrannhet och effektiviseringar. Vi har också pratat tidigare med Peter Ahlström från SBK angående ett samarbete mellan SBK och GK om att dela kod/kunskaper.

**Comment by Gullin** [comment]
Om inte verktygsgruppen redan har haft uppe frågan om utvecklingsspråk i projektet är det definitivt något som behöver hanteras i förvaltningsorganisationens utvecklargrupp (i Kartverktygsgruppen). Kan exempelvis tas upp i något som utvecklarmetodiken, utvecklingsprinciper eller utvecklarmanifest. Tror starkt på att man behöver låsa vad som används front end och back end i all nyutveckling. Eventuell ska man även lägga en road map för att porta de gamla lösningarna till de nya principerna/manifestet. Detta för att få en hanterbar långsiktig utvecklingsmiljö när man är flera om utvecklingen, både interna och externa. En av de viktiga delarna i den nya plattformen är precis en kompetenssäkring och kompetensutbyte med ett effektivt utnyttjande av de förvaltningsgemensamma resurserna. Dela är hela devisen i plattformen, de tre D:na (dela, dela med sig och delta).

**Comment by ulfmin** [comment]
Detta frågor hanteras i dokumentet "Riktlinjer Strategi utveckling och förvaltning" som ligger med i materialet som överlämnas till förvaltning.

**Comment by ulfmin** [comment]
Flyttad til kartagrupp efter möte 170518l
