### ISSUE TITLE
Lathund, Skins i CSM

### ISSUE THREAD

**Issue by RayTimlin** [malmomap/mmap-modules#64]
Utred och skriv manual för administratörer.
Gör skin för basplattform.
Lägg in kod i basplattform. (mmaptest) när koden är testad och acceptansgodkänd..

**Comment by ulfmin** [comment]
Gör symbolen mindre i lagerväljaren (samma storlek som i teckenförklaringen)

**Comment by ulfmin** [comment]
Lathund beställd av Sokigo 21/11-16, vi kör på CSM:s skins

**Comment by ulfmin** [comment]
Duplicate
