### ISSUE TITLE
Lagermeny-Hovringsbar kartsymbol

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#65]
Visa större kartsymbolbild när man hovrar symbolen i lagermenyn 
![image](https://cloud.githubusercontent.com/assets/5473068/17690199/48959d1a-638d-11e6-8202-d5a3f69a1655.png)

**Comment by RayTimlin** [comment]
Pga av stopp som gäller 3.12 och IE11 så undersöka jag detta

**Comment by RayTimlin** [comment]
We asked our GIS intern to see if he had any solutions for this problem.

Have placed his suggestion in here: http://mmapdev.sbkmalmo.local/spatialmap?profile=profile_malmogk

![bild](https://user-images.githubusercontent.com/13118484/29174134-a9b43a52-7de5-11e7-93d3-ba3682ae0d25.png)

Många av GKs lager ha ingen symboler, vore bra att ha att det ingen finns med istället för en tomma ruta.

Har ett forslag:
http://mmapdev.sbkmalmo.local/spatialmap?profile=profile_malmogk_ray

![bild](https://user-images.githubusercontent.com/13118484/29174317-39a9679a-7de6-11e7-94aa-5d9c9d99205a.png)

**Comment by RayTimlin** [comment]
Lite konstigt med 3.12 (nåt med CSS regler) men gick. @ulfmin - kan du kolla http://mmapdev1.intra.malmo.se/spatialmap?profile=mmap_grundplatta_gk och ge feedback
