### ISSUE TITLE
Utred kodning, mappstruktur, testning mm

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#68]
Var kodar vi och hur ser arbetsflödet ut. Hur ser mappstrukturen ut. Hur testas kod: Buggar, webbläsare, acceptanstest. Hur kan vi ha koden på Githhub? Hur länkar vi in olika ramverk, versionsproblematik. Hur väljer vi ramverk?

**Comment by johanlahti** [comment]
Jag har lagt upp ett förslag till modulstruktur.

_I korthet:_
- En **basklass** med standardfunktionalitet som alla moduler ska ha (t ex hämta konfiguration)
- Nya moduler **ärver egenskaper och metoder** från basklassen genom `class MyModule extends MMapBaseClass`

Den som kodar nya moduler behöver **inte** förstå hur byggprocessen fungerar utan behöver endast kopiera mallen och installera det nödvändiga (se README.md för helloWorld) med `npm install` samt `npm build`.

_Mer i detalj fungerar det på följande sätt när man skriver en ny modul:_
- Kopiera mallen
- Skriv `npm install` och skriv `npm build` när koden ska byggas (kräver att nodejs/npm är installerat)
- Kod skrivs i ES2015<= och transpileras till ES5 (d v s "gammel-JavaScript")
- npm och package.json används för att ange dependencies såsom jquery i package.json för den nya modulen
- Anpassa `deploy.xml`-filen så den pekar ut rätt filer i dist-mappen (som nu är översatta till ES5 som webbläsare/CSM förstår)

Utöver detta finns en del hjälp-metoder för eventuell testdriven-utveckling och t ex transpilering av stylus-filer. Men det är upp till respektive utvecklare att bestämma hur man vill koda och om man vill använda dessa (eller utvidga med andra funktioner).

**Comment by ulfmin** [comment]
Utredning görs av Sweco som leverat dokument med denna information (dokumen finns i kartverktygets mapp till förvaltningsfruppen. Dokumentet uppdateras kontinuerligt.

**Comment by ulfmin** [comment]
Duplicate
