### ISSUE TITLE
A04 Verktygsikon för zoom

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#7]
- Som användare vill jag ha en tydlig funktion i form av ett verktyg i kartfönstret för in och ut- zoomning i kartan. Om Mus används ska ytterligarte funktion för in och ut - zoomning  finnas i skrollhjulet. Ett verktyg är endast aktuellt på en PC då funktionen på en pekskärm fungerar med hjälp av fingerrörelse.
  Som användare vill jag kunna hålla i Shift-tangenten för att snabbt zooma till en ritad rektangel.
- Ett vedertaget verktyg synligt i kartan gör att användaren ser att funktionen finns. Skrollhjul tillsammans med pannoreringsverktyg (handen) är ett effektivare verktyg för att manövrera till önskad plats i kartan. Finns dessa två funktioner för att zooma i kartan kan + och - verktygen eventuellt slopas.
- [Många användare lär sig inte SHIFT - Drag för att zooma, det blir tydligare med ett zoomverktyg.]

**Comment by mozvey** [comment]
Ja, det finns zoom verktyg som man kan använda manuelt att klicka på och zommera eller använda rektangel-zoom. Man kan använda mus-skrollhjulet. Gällande Ipad och tuoch-skärmor man kan zooma ner/ upp med fingerrörelse.
