### ISSUE TITLE
A05 Panorera och zooma

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#8]
- Som användare vill jag kunna ändra kartans centrering och zoomnivå genom att dra/peka/nypa i kartan samt genom piltangenterna så att jag enkelt kan se Malmö ur många olika synvinklar. Som användare vill jag också kunna klicka på pil-/zoomknappar i kartan för att panorera/zooma eller hålla i Shift-tangen för att zooma till rektangel.

**Comment by RayTimlin** [comment]
Tror detta är klar

//Ray
