### ISSUE TITLE
API till CSM, öppna CSM med URL + parametrar

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#84]
ACL och Lotten definierar vad denna modul ska göra

**Comment by ulfmin** [comment]
Vi ska ta upp denna när vi träffar Sweco-Danmark 15 juni

**Comment by RayTimlin** [comment]
GK också har ett intresse i detta projekt via en liknande kopplingen till sin projekt system, Antura. En användare i Antura skulle klicka på en projektnummer/link som tar de till motsvarande projekt i CSM. Det kan vara samma sak med andra system t ex grävningssystem.

**Comment by msfk-annmal** [comment]
Behöver en funktion som kan implementeras i Malmö stads olika verksamhetssystem, en funktion där användaren kan klicka, i olika verksamhetssystem, och en URL skapas. En URL som sedan öppnar en inzoomad mmap-karta med de/det aktuella objekt, från verksamhetssystemet, markerade.
 
Det är många olika typer av objekt i våra verksamhetssystem som skall kunna kopplas mot kartan:
 - avtalsnummer från avtalssystem
-  fastighetsbeteckningar/-id och gatuadresser från många olika typer av system
-  projektnummer från projektledningssystem
-  ärendenummer från ärendehanteringssystem
-  m fl 
Det skall även vara möjligt att skicka id-referenser till FLERA objekt via denna funktion, ex flera fastighetsid.
 
URLen till en mmap-karta (specifik site och profil skall kunna anges) skall sättas ihop med sökparametrar och ett/flera id.Exempel på dagens existerande funktion:
http://fkmap.malmo.se/fkkartan/?fnr=12041008;12308501
(1)	http://fkmap.malmo.se/fkkartan     (2) /?fnr    (3) =12041008;12308501

1. URL som öppnar kartan, här ska man kunna ange en specifik site och profil
2. parameter som visar typen av objekt (avtal, fastighet, projekt, ärende m m) som kartan skall söka efter, specifikt theme
3. själva värdet/värdena som det skall sökas efter (avtalsnummer, fastighetsid, projektnr, ärendenr)

Skulle kunna se ut så här, ex:
(1)	http:// site + profil      (2) /?theme=Fastighet&fnr    (3)=12041008;12308501
 
 
PS: Samma funktion skall senare kunna vidareutvecklas och användas från "andra hållet", d v s från webkartan till våra verksamhetssystem. URL till olika verksamhetssystem skall kunna sättas ihop med sökparametrar och ett id.
Detta blir dock ett separat ärende senare.

**Comment by ulfmin** [comment]
9/6   
Jag har kollat Ann-Charlottes anteckningar om API funktionen och jag har inte något mer att tillägga.
Mvh
Lotten

**Comment by ulfmin** [comment]
Flyttad till Teams
