### ISSUE TITLE
A06 VERKTYGSMENY

### ISSUE THREAD

**Issue by ulfmin** [malmomap/mmap-modules#9]
Som användare vill jag kunna överblicka vilka verktyg som finns tillgängliga samt välja att aktivera ett eller flera verktyg så att jag kan anpassa kartans funktionalitet efter mina behov. Detta ska också fungera responsivt (på små skärmar) - gäller allt.

**Comment by mozvey** [comment]
Det finns inte nu sådana möjlighet.

**Comment by ulfmin** [comment]
Lägg i Sprint för Gränssnitt
